services:
  - type: web
    id: srv-d8e2o4v7f7vs73cofong
    name: flask-poc-1
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
